# Generated by Django 2.1.1 on 2018-09-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180918_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='photo',
            field=models.ImageField(null=True, upload_to='clients_photos'),
        ),
    ]
