# Generated by Django 2.1 on 2018-09-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
