# Generated by Django 2.1.1 on 2018-10-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='event',
        ),
        migrations.AddField(
            model_name='rating',
            name='commented',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='type',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
