# Generated by Django 2.1 on 2018-10-15 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_delete_event'),
        ('event', '0005_auto_20181015_0041'),
        ('main', '0011_auto_20181014_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='commented',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='type',
        ),
        migrations.AddField(
            model_name='rating',
            name='event_rated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user_rated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User_animal'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
