# Generated by Django 2.1.1 on 2018-10-16 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20181015_0041'),
        ('main', '0013_auto_20181016_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rated',
        ),
        migrations.AddField(
            model_name='rating',
            name='event_rated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
    ]
