# Generated by Django 2.1 on 2018-09-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180926_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_animal',
            name='photo',
            field=models.ImageField(null=True, upload_to='clients_photos'),
        ),
    ]
