# Generated by Django 2.1 on 2018-09-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='King',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('rg', models.CharField(max_length=20)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('andreess', models.CharField(max_length=50)),
                ('since', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
