# Generated by Django 2.1.1 on 2018-09-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_king_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='king',
            name='photo',
        ),
    ]
