# Generated by Django 2.1.1 on 2018-09-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_king_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='king',
            name='andreess',
        ),
        migrations.RemoveField(
            model_name='king',
            name='cpf_cnpj',
        ),
        migrations.RemoveField(
            model_name='king',
            name='email',
        ),
        migrations.RemoveField(
            model_name='king',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='king',
            name='job',
        ),
        migrations.RemoveField(
            model_name='king',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='king',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='king',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='king',
            name='since',
        ),
    ]
