# Generated by Django 2.1.1 on 2018-09-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20180915_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='king',
            name='andress',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='king',
            name='cpf_cnpj',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='king',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='king',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='king',
            name='job',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='king',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='king',
            name='rg',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='king',
            name='since',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
