# Generated by Django 2.1.1 on 2018-09-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20180915_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='king',
            name='photo',
            field=models.ImageField(null=True, upload_to='clients_photos'),
        ),
    ]
