# Generated by Django 2.1.1 on 2018-09-16 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_king_password1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='king',
            old_name='password1',
            new_name='password',
        ),
    ]
