# Generated by Django 2.1.1 on 2018-09-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_auto_20180916_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='king',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
