# Generated by Django 2.1.1 on 2018-09-17 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_king_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='king',
            name='email',
        ),
        migrations.RemoveField(
            model_name='king',
            name='password',
        ),
        migrations.RemoveField(
            model_name='king',
            name='user_name',
        ),
    ]
