# Generated by Django 2.1 on 2018-09-23 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_usuario_username'),
        ('main', '0003_usuario_photo'),
    ]

    operations = [
    ]
