# Generated by Django 2.1.1 on 2018-10-14 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181014_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
