# Generated by Django 2.1.1 on 2018-10-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number_ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
