# Generated by Django 2.1.1 on 2018-10-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_number_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='number_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
