# Generated by Django 2.1.1 on 2018-10-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20181015_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
