# Generated by Django 2.1 on 2018-10-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20181001_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_animal',
            name='type',
            field=models.CharField(default='Animal', max_length=6),
        ),
    ]
