# Generated by Django 2.1 on 2018-10-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20181001_1715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
