# Generated by Django 2.1 on 2018-10-16 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_wishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_wishes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User_animal'),
        ),
    ]
