# Generated by Django 2.1 on 2018-10-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_wishes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_wishes',
            name='price',
            field=models.CharField(blank=True, choices=[('free', 'Sim'), ('10~20', 'De R$10 até R$20'), ('20~30', 'De R$20 até R$30'), ('>30', 'Mais de R$30')], max_length=5, null=True),
        ),
    ]
